### ISSUE TITLE
Player randomly stops playing

### ISSUE THREAD

**Issue by YuzuTheNeko** [XzFirzal/discord-media-player#3]
**Problem:**
The player stops playing the track after some time.

**Code:**
```js
player.play("url")
```

**More Details:**
- discord-media-player version: latest
- Node.js version: v16.6.1
- Operating system: Windows

**Manager Options:**
- cache: true
- youtubeOptions:
- soundcloudClient:
- createAudioPlayer():

**Custom Implementations:**
- AudioPlayer: link or code
- CacheManager: link or code

**Comment by XzFirzal** [comment]
this is somewhat issue on ytdl-core itself

**Comment by XzFirzal** [comment]
https://github.com/XzFirzal/discord-media-player/commit/749d2daec6e0755e02aaf807d0774afc8ab6d781
